### ISSUE TITLE
Reformat code

### ISSUE THREAD

**Issue by HimmelKreis4865** [supercrafter333/BlockAPI#3]
Please consider reformating your code. 👍🏼 

Specify **whether** you wanna use 
```php
function () {

}
```
or 
```php
function()
{
}
```
Always **use camel case for methods**, try to only - add nouns (which first letter should be uppercase) in your **class names** and maybe think about adding phpdocs for better documentation in the raw api.

As a last step you could **improve your imports**, some of them are useless. ^^

HimmelKreis4865

**Comment by supercrafter333** [comment]
Thank you. I will do it someday.

PS: kannst auch auf Deutsch beim nächsten Mal schreiben xD

**Comment by HimmelKreis4865** [comment]
Englisch ist bei issues eine deutlich bessere Sprache, damit können es die meisten Menschen auf der Welt auch lesen und somit erübrigen sich vermutlich weitere Fragen :3

**Comment by supercrafter333** [comment]
Ja, stimmt auch wieder xD
