### ISSUE TITLE
Unique config-constructor calls

### ISSUE THREAD

**Issue by DerDevHD** [supercrafter333/BlockAPI#4]
Hi!

I've just discoverd your plugin, and saw some things that annoyed me.
For instance, why do you use at [supercrafter333/BlockAPI/API/BlockAPI](https://github.com/supercrafter333/BlockAPI/blob/master/src/supercrafter333/BlockAPI/API/BlockAPI.php#L19) this way, and add the second constructor parameter, but in [supercrafter333/BlockAPI/API/OffBlockAPI](https://github.com/supercrafter333/BlockAPI/blob/master/src/supercrafter333/BlockAPI/API/OffBlockAPI.php#L21) you left that.

And also, the first method I mentioned is very unsafe, because the numeric ids of config-types can always change unexpectedly.
I would recommend, to use the constant `Config::YAML` all the time, for better readability.

Best regards and a late merry christmas.

ps. pls don't blame me for my bad english and grammer

**Comment by supercrafter333** [comment]
I'll do it better time to time.

Du kannst übrigens auch Deutsch schreibe, bin Deutcher :)

**Comment by supercrafter333** [comment]
I'll change the config ids (2) to ``Config::YAML`` soon. But I don't think that I change other things.

**Comment by supercrafter333** [comment]
done
